# Generated by Django 5.1.7 on 2025-03-23 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izde', '0002_remove_house_location_location_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
