# Generated by Django 5.1.7 on 2025-03-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izde', '0002_remove_house_category_house_property_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
