# Generated by Django 5.1.7 on 2025-03-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izde', '0002_remove_agentprofile_languages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agent'},
        ),
    ]
