# Generated by Django 5.1.7 on 2025-03-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izde', '0003_alter_agentprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='social_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
