# Generated by Django 5.1.7 on 2025-03-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izde', '0003_delete_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='position_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='position_ky',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='position_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='agentrating',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrating',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrating',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='area_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='area_name_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='area_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_name_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_ky',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_ru',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='hobby_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='hobby_name_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='hobby_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='descriptions_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='descriptions_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='descriptions_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='house_name_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='house_name_ky',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='house_name_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='house_roules_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='house_roules_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='house_roules_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='housereview',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='housereview',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='housereview',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='languages',
            name='language_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='languages',
            name='language_name_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='languages',
            name='language_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_name_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='selectedwork',
            name='description_en',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='selectedwork',
            name='description_ky',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='selectedwork',
            name='description_ru',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='selectedwork',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='selectedwork',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='selectedwork',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='platform_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='platform_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='platform_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
